version: '3.2'

services:
  reverseproxy:
    depends_on:
      - codescene
    image: nginx:1.19
    ports:
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  codescene:
    image: empear/codescene:latest
    restart: always
    volumes:
      - ./codescene:/codescene
        # environment:
          # raise codescene log level for troubleshooting
          # - CODESCENE_LOG_LEVEL=DEBUG
          # provide custom java options, e.g. proxy settings for project management integration
          # - JAVA_OPTIONS=-Dhttp.proxyHost=my.proxy.com -Dhttp.proxyPort=3128 -Dhttps.proxyHost=my.proxy.com -Dhttps.proxyPort=3128
